data:
  cache_dir: "data"
  start_date: "2015-01-01"
  end_date: "2025-08-01"
  provider: "yfinance"  # or "iex"
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
reproducibility:
  seed: 42
  
parallel:
  n_jobs: -1  # Use all cores
  backend: "loky"