horizons: [1, 5, 21]  # 1D, 1W, 1M
rank_weights: [0.1, 0.3, 0.6]  # Weight for combining horizons

features:
  windows: [5, 10, 14, 20, 50]
  indicators:
    momentum: ["rsi", "roc", "stoch", "cci", "williams", "mom"]
    trend: ["sma", "ema", "macd", "bb", "adx", "ichimoku"]
    volatility: ["atr", "std", "donchian", "bb_width"]
    volume: ["obv", "mfi", "volume_roc", "ad"]
    relative: ["rel_strength_spy", "dist_52w_high", "dist_52w_low"]
    
preprocessing:
  winsorize_pct: 0.01  # Clip at 1% and 99% percentiles
  standardize: true
  nan_strategy: "drop"  # or "forward_fill"
  
feature_selection:
  method: "lasso"  # or "rfe"
  alpha: 0.001  # For LASSO
  n_features: 100  # For RFE

  models:
  - type: "lasso"
    alpha: 0.001
  - type: "random_forest"
    n_estimators: 100
    max_depth: 10
    min_samples_split: 20
  - type: "lightgbm"
    n_estimators: 1000
    learning_rate: 0.01
    max_depth: 5
    num_leaves: 31
    subsample: 0.8
    colsample_bytree: 0.8
    
cv:
  n_splits: 5
  embargo_days: 21
  
ranking:
  top_k: 2000
  score_method: "weighted"  # or "primary"
  
output:
  predictions_dir: "data/fine_predictions"
  models_dir: "data/fine_models"