n_days: 30  # Predict 30-day vector

features:
  windows: [60, 120]
  timeseries:
    moments: ["variance", "skewness", "kurtosis"]
    acf_lags: 20
    hurst: true
    entropy: true
    fractal_dim: false
    trend: true
    drawdown: true
    up_down_ratio: true
    
tsfresh:
  enabled: false  # Optional, computationally expensive
  max_features: 50
  
model:
  type: "multi_output"  # or "independent"
  estimator: "lightgbm"
  params:
    n_estimators: 1000
    learning_rate: 0.01
    max_depth: 5
    num_leaves: 31
    
aggregation:
  method: "cum_return"  # or "sharpe_like"
  top_k: 500
  
calibration:
  enabled: false
  method: "isotonic"  # or "sigmoid"
  
output:
  predictions_dir: "data/rerank_predictions"
  models_dir: "data/rerank_models"